Fixed a typo in github actions -- subcommandstest -> subcommandtest

diff --git a/.github/workflows/macs2.yml b/.github/workflows/macs2.yml
--- a/.github/workflows/macs2.yml
+++ b/.github/workflows/macs2.yml
@@ -42,7 +42,7 @@ jobs:
       run: |
         cd test
         ./test.sh subcommandtest
-        flag=1;for i in `ls subcommandstest_run_*/*.log`;do echo $i;egrep -i "error|warning" $i;let "flag&=$?";done;if [[ $flag == 0 ]];then false;fi
+        flag=1;for i in `ls subcommandtest_run_*/*.log`;do echo $i;egrep -i "error|warning" $i;let "flag&=$?";done;if [[ $flag == 0 ]];then false;fi
         cd ..
     - name: Build sdist
       run: |
