update github actions yml

diff --git a/.github/workflows/macs2.yml b/.github/workflows/macs2.yml
--- a/.github/workflows/macs2.yml
+++ b/.github/workflows/macs2.yml
@@ -38,12 +38,13 @@ jobs:
       run: |
         pip install pytest
         pytest
-    - name: Test with small data files
-      run: 
+    - name: Run tests with small data files
+      run: |
         cd test
         ./test.sh subcommandtest
-        flag=1;for i in `ls subcommandtest_run_*/*.log`;do echo $i;egrep -i "error|warning" $i;let "flag&=$?";done;if [[ $flag == 0 ]];then false;fi
-        cd ..
+	cd ..
+    - name: Check warn/error from previous test
+        flag=1;for i in `ls test/subcommandtest_run_*/*.log`;do echo $i;egrep -i "error|warning" $i;let "flag&=$?";done;if [[ $flag == 0 ]];then false;fi
     - name: Build sdist
       run:
         python setup.py sdist
